In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('beer_reviews.csv')

In [6]:
df.head()

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586614 entries, 0 to 1586613
Data columns (total 13 columns):
brewery_id            1586614 non-null int64
brewery_name          1586599 non-null object
review_time           1586614 non-null int64
review_overall        1586614 non-null float64
review_aroma          1586614 non-null float64
review_appearance     1586614 non-null float64
review_profilename    1586266 non-null object
beer_style            1586614 non-null object
review_palate         1586614 non-null float64
review_taste          1586614 non-null float64
beer_name             1586614 non-null object
beer_abv              1518829 non-null float64
beer_beerid           1586614 non-null int64
dtypes: float64(6), int64(3), object(4)
memory usage: 157.4+ MB

In [8]:
df.isnull().sum()

brewery_id                0
brewery_name             15
review_time               0
review_overall            0
review_aroma              0
review_appearance         0
review_profilename      348
beer_style                0
review_palate             0
review_taste              0
beer_name                 0
beer_abv              67785
beer_beerid               0
dtype: int64

In [16]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1518478 entries, 0 to 1586613
Data columns (total 13 columns):
brewery_id            1518478 non-null int64
brewery_name          1518478 non-null object
review_time           1518478 non-null int64
review_overall        1518478 non-null float64
review_aroma          1518478 non-null float64
review_appearance     1518478 non-null float64
review_profilename    1518478 non-null object
beer_style            1518478 non-null object
review_palate         1518478 non-null float64
review_taste          1518478 non-null float64
beer_name             1518478 non-null object
beer_abv              1518478 non-null float64
beer_beerid           1518478 non-null int64
dtypes: float64(6), int64(3), object(4)
memory usage: 162.2+ MB

In [25]:
#order reviews and drop duplicates
df.sort_values('review_overall', ascending=False)
df = df.drop_duplicates(subset=['review_profilename', 'beer_name'], keep='first')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1496263 entries, 0 to 1586613
Data columns (total 13 columns):
brewery_id            1496263 non-null int64
brewery_name          1496263 non-null object
review_time           1496263 non-null int64
review_overall        1496263 non-null float64
review_aroma          1496263 non-null float64
review_appearance     1496263 non-null float64
review_profilename    1496263 non-null object
beer_style            1496263 non-null object
review_palate         1496263 non-null float64
review_taste          1496263 non-null float64
beer_name             1496263 non-null object
beer_abv              1496263 non-null float64
beer_beerid           1496263 non-null int64
dtypes: float64(6), int64(3), object(4)
memory usage: 159.8+ MB

In [34]:
#Drop reviews of less than 1
df = df.loc[df.review_overall >= 1]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1496256 entries, 0 to 1586613
Data columns (total 13 columns):
brewery_id            1496256 non-null int64
brewery_name          1496256 non-null object
review_time           1496256 non-null int64
review_overall        1496256 non-null float64
review_aroma          1496256 non-null float64
review_appearance     1496256 non-null float64
review_profilename    1496256 non-null object
beer_style            1496256 non-null object
review_palate         1496256 non-null float64
review_taste          1496256 non-null float64
beer_name             1496256 non-null object
beer_abv              1496256 non-null float64
beer_beerid           1496256 non-null int64
dtypes: float64(6), int64(3), object(4)
memory usage: 159.8+ MB

In [35]:
df.head()

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

In [36]:
df.to_csv('beer_reviews_clean.csv')